name: note_hub
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  hexcolor: ^3.0.1
  connectivity_plus: ^5.0.2
  conditional_builder_null_safety: ^0.0.6
  lottie: ^3.0.0
  permission_handler: ^11.2.1
  cached_network_image: ^3.3.1
  pdf: ^3.10.8
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  share_plus: ^7.2.2
  #  url_launcher: ^6.2.5
  # local data
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2

  # firebase 
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.3
  image_picker: ^1.0.7
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
